-- Force RLS policies to apply even to table owner
-- This is necessary because neondb_owner owns the tables

ALTER TABLE "User" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Brand" FORCE ROW LEVEL SECURITY;
ALTER TABLE "UserBrand" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Campaign" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SubCampaign" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Integration" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Metric" FORCE ROW LEVEL SECURITY;
ALTER TABLE "ShareLink" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Invoice" FORCE ROW LEVEL SECURITY;
ALTER TABLE "IgExtraction" FORCE ROW LEVEL SECURITY;
ALTER TABLE "TtExtraction" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Industry" FORCE ROW LEVEL SECURITY;
ALTER TABLE "IndustrySubType" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Platform" FORCE ROW LEVEL SECURITY;
ALTER TABLE "Channel" FORCE ROW LEVEL SECURITY;
ALTER TABLE "CampaignChannel" FORCE ROW LEVEL SECURITY;
ALTER TABLE "SubCampaignChannel" FORCE ROW LEVEL SECURITY;
ALTER TABLE "AppConfig" FORCE ROW LEVEL SECURITY;
